print("kek", 'TRYNDEC HAPPENS! YOU HAVE BEEN VZLOMAN', 'TRYNDEC HAPPENS! YOU HAVE BEEN VZLOMAN', 'TRYNDEC HAPPENS! YOU HAVE BEEN VZLOMAN')
a=2
if a<17:
    print("mem", 'TRYNDEC HAPPENS! YOU HAVE BEEN VZLOMAN', 'TRYNDEC HAPPENS! YOU HAVE BEEN VZLOMAN', 'TRYNDEC HAPPENS! YOU HAVE BEEN VZLOMAN')